export const ALL_AUTOTASKS = [
    { name: 'checkin', reward: 1000 },
    { name: 'friend-invite', reward: 5000 },
    { name: 'wallet', reward: 5000 },
    { name: 'welcome-bonus', reward: 1000 },
    { name: 'shere-in-stories', reward: 10000 },
    { name: 'account-bio', reward: 10000 },
    { name: 'web-url', reward: 100 },
    { name: 'open-x', reward: 100 },
    { name: 'open-tg', reward: 100 },
    { name: 'open-youtube', reward: 100 },
    { name: 'open-tiktok', reward: 100 },
    { name: 'open-reddit', reward: 100 },
    { name: 'open-discord', reward: 100 },
    { name: 'open-whitepaper', reward: 10000 },
    { name: 'open-pitchdek', reward: 10000 },
    { name: 'watch-start-video', reward: 5000 },
  ];